Repository finos/morphir-elm, pull requests merged in 2020-09, with the labels that each got.

#135 Fix Elm package link
  README.md
Labels: cla-present

#137 Fix associativity
  src/Morphir/Elm/Frontend.elm
  tests/Morphir/Elm/FrontendTests.elm
Labels: cla-present

#138 Resolve constructor patterns
  src/Morphir/Elm/Frontend.elm
  tests/Morphir/Elm/FrontendTests.elm
Labels: bug, cla-present

#139 Generate case objects instead of case classes for no-arg constructors
  src/Morphir/Scala/Backend.elm
Labels: bug, cla-present

#142 Enhancements on Scala code generation
  src/Morphir/Scala/Backend.elm
Labels: cla-present

#132 fix link to contribution guide
  README.md
Labels: cla-present

#143 Scala gen enhancements
  src/Morphir/Scala/AST.elm
  src/Morphir/Scala/Backend.elm
  src/Morphir/Scala/PrettyPrinter.elm
Labels: cla-present

#146 Added overview diagram
  README.md
  docs/assets/package-overview.png
Labels: cla-present

#147 Updated diagram
  docs/assets/package-overview.png
Labels: cla-present

#150 Removed stdout/stdin defaults and replaced with 'morphir-ir.json'.
  cli/cli.js
  cli/morphir-elm-gen.js
  cli/morphir-elm-make.js
  package.json
Labels: cla-present

#151 Different annotation type between types and values
  cli/src/Morphir/Elm/DaprCLI.elm
  src/Morphir/Elm/Frontend.elm
  src/Morphir/Elm/Frontend/Resolve.elm
  src/Morphir/IR/Module.elm
  src/Morphir/IR/Module/Codec.elm
  src/Morphir/IR/Package.elm
  src/Morphir/IR/Package/Codec.elm
  src/Morphir/IR/SDK.elm
  src/Morphir/IR/SDK/Basics.elm
  src/Morphir/IR/SDK/Char.elm
  src/Morphir/IR/SDK/Dict.elm
  src/Morphir/IR/SDK/List.elm
  src/Morphir/IR/SDK/Maybe.elm
  src/Morphir/IR/SDK/Regex.elm
  src/Morphir/IR/SDK/Result.elm
  src/Morphir/IR/SDK/String.elm
  src/Morphir/IR/SDK/Tuple.elm
  src/Morphir/Scala/Backend.elm
  tests/Morphir/Elm/Frontend/ResolveTests.elm
  tests/Morphir/Elm/FrontendTests.elm
Labels: cla-present

#149 Removed key from API and added sample model with tests. #148
  src/Morphir/IR/SDK.elm
  src/Morphir/IR/SDK/StatefulApp.elm
  src/Morphir/SDK/StatefulApp.elm
  tests-integration/reference-model/elm.json
  tests-integration/reference-model/morphir.json
  tests-integration/reference-model/src/Morphir/Reference/Model/BooksAndRecords.elm
  tests-integration/reference-model/tests/Morphir/Reference/Model/BooksAndRecordsTests.elm
Labels: cla-present

#153 Split out value and type annotations on value definitions. #152
  src/Morphir/Elm/Frontend.elm
  src/Morphir/Elm/Frontend/Resolve.elm
  src/Morphir/IR/Module.elm
  src/Morphir/IR/Module/Codec.elm
  src/Morphir/IR/Package.elm
  src/Morphir/IR/Package/Codec.elm
  src/Morphir/IR/SDK.elm
  src/Morphir/IR/SDK/Basics.elm
  src/Morphir/IR/SDK/Char.elm
  src/Morphir/IR/SDK/Common.elm
  src/Morphir/IR/SDK/Dict.elm
  src/Morphir/IR/SDK/List.elm
  src/Morphir/IR/SDK/Maybe.elm
  src/Morphir/IR/SDK/Regex.elm
  src/Morphir/IR/SDK/Result.elm
  src/Morphir/IR/SDK/StatefulApp.elm
  src/Morphir/IR/SDK/String.elm
  src/Morphir/IR/SDK/Tuple.elm
  src/Morphir/IR/Value.elm
  src/Morphir/IR/Value/Codec.elm
  src/Morphir/Scala/Backend.elm
  tests/Morphir/Elm/Frontend/ResolveTests.elm
  tests/Morphir/Elm/FrontendTests.elm
Labels: cla-present, enhancement

#157 Scala gen type inference fix
  cli/src/Morphir/Elm/CLI.elm
  elm.json
  src/Morphir/Elm/Frontend.elm
  src/Morphir/IR/Distribution.elm
  src/Morphir/IR/Distribution/Codec.elm
  src/Morphir/IR/Module.elm
  src/Morphir/IR/Module/Codec.elm
  src/Morphir/IR/Package.elm
  src/Morphir/IR/Package/Codec.elm
  src/Morphir/IR/SDK.elm
  src/Morphir/IR/SDK/Basics.elm
  src/Morphir/IR/SDK/Char.elm
  src/Morphir/IR/SDK/Common.elm
  src/Morphir/IR/SDK/Dict.elm
  src/Morphir/IR/SDK/List.elm
  src/Morphir/IR/SDK/LocalDate.elm
  src/Morphir/IR/SDK/Maybe.elm
  src/Morphir/IR/SDK/Regex.elm
  src/Morphir/IR/SDK/Result.elm
  src/Morphir/IR/SDK/StatefulApp.elm
  src/Morphir/IR/SDK/String.elm
  src/Morphir/IR/SDK/Tuple.elm
  src/Morphir/IR/Type/Codec.elm
  src/Morphir/IR/Value.elm
  src/Morphir/IR/Value/Codec.elm
  src/Morphir/Scala/Backend.elm
  src/Morphir/Scala/PrettyPrinter.elm
  tests-integration/reference-model/src/Morphir/Reference/Model/Values.elm
  tests/Morphir/Elm/FrontendTests.elm
Labels: cla-present

#158 Scala gen type inference fix
  src/Morphir/Scala/AST.elm
  src/Morphir/Scala/Backend.elm
  src/Morphir/Scala/PrettyPrinter.elm
  tests-integration/reference-model/src/Morphir/Reference/Model/Types.elm
  tests-integration/reference-model/src/Morphir/Reference/Model/Values.elm
Labels: cla-present

#159 Update README.md
  README.md
Labels: cla-present

#164 Temporarily revert back to uncurried calls until we come up with a co…
  src/Morphir/Scala/Backend.elm
Labels: cla-present
